development:
  adapter: postgresql
  database: autoservice_development
  host: localhost
  username: postgres
  password: password
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: autoservice_test
  host: localhost
  username: postgres
  password: password
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: autoservice_production
  host: localhost
  username: isaeviv
  password: aqwsderfgtyhju
  pool: 5
  timeout: 5000
